FROM ubuntu:22.04

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# 设置时区 
ARG TZ=Asia/Shanghai 
ENV TZ ${TZ}  
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  

# 更新源，替换为阿里云源 
RUN sed -i "s/security.ubuntu.com/mirrors.aliyun.com/" /etc/apt/sources.list && \     
  sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/" /etc/apt/sources.list && \     
  sed -i "s/security-cdn.ubuntu.com/mirrors.aliyun.com/" /etc/apt/sources.list && \
  apt clean

# 更新源，安装相应工具 
RUN apt update && apt install -y \     
  zsh \     
  vim \     
  wget \     
  curl \    
  git 
RUN chsh -s /bin/zsh  

#  安装 oh-my-zsh 并设置zsh为默认shell
RUN sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

# 安装 node 
ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=18
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
  . "$NVM_DIR/nvm.sh" && \     
  nvm install $NODE_VERSION && \     
  nvm alias default $NODE_VERSION && \     
  nvm use default && \     
  npm config set registry https://registry.npm.taobao.org

# 设置环境变量，使nvm和node在shell中可用
RUN echo 'export NVM_DIR="$HOME/.nvm"' >> /root/.zshrc \
    && echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> /root/.zshrc \
    && echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> /root/.zshrc

# 设置工作目录，可根据实际需求更改
WORKDIR /workdir

# 开放端口给 Node.js 应用
EXPOSE 3000

# 将Docker容器的标准输入保持打开，以便运行交互式Shell
CMD ["zsh"]